version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      pnpm-dependencies:
        patterns:
          - '*'
